name: "🙋 회의"
description: 팀원들과 논의할 사항이 있으신가요?
title: "[MEETING] "
labels: ["🙋 meeting"]
body:
  - type: input
    attributes:
      label: 🙋🏻 참가 인원
      description: "회의에 참석할 인원의 이름을 입력해주세요."
      placeholder: "예: 홍길동, 김철수"
    validations:
      required: true

  - type: input
    attributes:
      label: 🕒 회의 시간
      description: "회의 시간을 입력해주세요."
      placeholder: "예: 2024-06-01 10:00 AM"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 설명
      description: "회의에 대한 간단한 설명을 입력해주세요."
      placeholder: "회의에 대한 간단한 설명을 작성해주세요."
    validations:
      required: true

  - type: textarea
    id: meeting-agenda
    attributes:
      label: 📋 회의 안건
      description: "회의에서 논의할 안건을 구체적으로 작성해주세요."
      placeholder: |
        - [ ] 안건 1
        - [ ] 안건 2
        - [ ] 안건 3
    validations:
      required: true

  - type: input
    attributes:
      label: ⏳ 추정 시간
      description: "회의에 예상되는 소요 시간을 입력해주세요."
      placeholder: "예: 1시간"
    validations:
      required: false

  - type: input
    attributes:
      label: ⌛ 소요 시간
      description: "회의에 실제로 소요된 시간을 입력해주세요."
      placeholder: "예: 1.5시간"
    validations:
      required: false
